# Generated by Erlang.mk. Edit at your own risk!

src/db.erl:: src/util.erl; @touch $@
src/offers_handler.erl:: src/db.erl src/util.erl; @touch $@
src/orders_handler.erl:: src/db.erl src/util.erl; @touch $@

COMPILE_FIRST += util db
